### ISSUE TITLE
Other microservices can't get configuration when deploy on Docker

### ISSUE THREAD

**Issue by TranNgocKhoa** [spring-petclinic/spring-petclinic-microservices#121]
I'm trying to create another version of your project.

But I'm stuck in this:
When I deploy **Config-Server**, **Discovery-Server, Api-Gateway**. **Config-Server** worked well. But it doesn't for remaining modules.
**Discovery-Server** and **Api-Gateway** can't connect to **Config-Server** to get configuration.
I'm sorry beacuse of my English grammar.
Please help.
Thank you!

This is my respository [https://github.com/TranNgocKhoa/doctor-searching](https://github.com/TranNgocKhoa/doctor-searching)

This is my `bootstrap.yml` for **Discovery** and **Gateway**:

```
spring:
  cloud:
    config:
      uri: http://config-server:8888

  application:
    name: discovery-server
```

```
spring:
  cloud:
    config:
      uri: http://config-server:8888

  application:
    name: discovery-server
```

Gateway `application.yml`

```
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
```
